INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (420,"VAN HOOL");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (470,"SUPACAT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (366,"SEDDON ATKINSON");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (362,"SCAMMELL");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (372,"STEYR");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (180,"JENSEN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (975,"M.O.D. LANDROVER TUM");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (163,"IVECO FORD TRUCKS");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (281,"OPTARE");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (102,"FIAT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (376,"SINOTRUK");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (45,"CITROEN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (4,"ALBION");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (60,"DAF");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (445,"ZASTAVA");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (162,"IVECO");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (20,"BEDFORD");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (202,"KASSBOHRER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (242,"MAGIRUS DEUTZ");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (64,"DIAMOND");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (121,"GENERAL MOTORS (GMC)");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (979,"M.O.D. MAN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (390,"TDS");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (532,"VAUXHALL");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (343,"ROMAN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (246,"MERCEDES BENZ");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (383,"TERBERG");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (973,"M.O.D. Thales");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (981,"M.O.D. LEYLAND/DAF");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (44,"CHEVROLET");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (360,"SAVIEM");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (422,"VOLKSWAGEN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (83,"ENASA");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (371,"SISU");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (26,"BRISTOL");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (41,"CHARGE");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (105,"FORD");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (452,"MULTICAR");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (262,"NEOPLAN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (986,"M.O.D. SEDDON/ATKINS");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (100,"FAUN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (377,"AMERICAN LE FRANCE");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (107,"FREIGHT ROVER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (989,"M.O.D. DAIMLER PUCH");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (309,"FAW");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (341,"REO");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (126,"GUY");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (62,"DENNIS");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (201,"KARRIER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (424,"WESTERN STAR");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (5,"ALVIS");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (977,"M.O.D. NAVISTAR DEFENSE");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (441,"WHITE");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (976,"M.O.D. IST");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (250,"MITSUBISHI");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (28,"BUSSING");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (401,"UNIC");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (369,"SHELVOKE & DREWRY");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (546,"AVIA");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (448,"SCHORING");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (301,"PEGASO");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (340,"RENAULT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (140,"HANOMAG");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (258,"MULTICAR");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (141,"HINO");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (984,"M.O.D. FODEN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (66,"DODGE");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (241,"MACK");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (243,"MAN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (9,"AUSTIN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (449,"OMNI");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (302,"PEUGEOT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (157,"JOHNSTON");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (368,"SHELVOKE");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (255,"MUNICIPAL TRAILERS");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (363,"SCANIA");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (444,"LEYLAND BUS");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (21,"BERLIET");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (203,"KENWORTH");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (23,"BMC");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (93,"Electra");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (221,"LA FRANCE");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (227,"LEYLAND REDLINE");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (106,"FREIGHTLINER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (345,"ROBERTS LEYLAND");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (303,"PETERBILT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (257,"MOTOR IBERICA");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (384,"THORNYCROFT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (266,"NISSAN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (983,"M.O.D. VOLVO");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (985,"M.O.D. M3 BRIDGING");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (12,"AWD");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (124,"GINAF");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (245,"MCW");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (402,"UNIMOG");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (342,"REYNOLDS BOUGHTON");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (46,"COMMER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (547,"AL-KO KOBER LIMITED");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (988,"M.O.D. LAND ROVER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (367,"SENTINEL");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (561,"Tatra");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (980,"M.O.D. BEDFORD");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (160,"INTERNATIONAL");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (228,"LANDMASTER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (223,"LAND ROVER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (364,"SEADYKE");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (978,"M.O.D. SUPERCAT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (447,"IFA");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (391,"IVECO MAGIRUS");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (990,"M.O.D. RENAULT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (80,"EBRO");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (380,"TALBOT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (982,"M.O.D. SCAMMEL");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (224,"LEYLAND");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (225,"LDV");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (82,"ERF");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (423,"VOLVO");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (370,"SHELVOKE DEMPSTER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (104,"FODEN");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (450,"BUCHER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (527,"DAEWOO");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (974,"M.O.D. Foxhound LPPV");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (51,"CHASSIS DEVELOPEMENT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (446,"SCHMIDT");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (387,"TOYOTA");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (253,"MORRIS");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (442,"WILLEME");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (451,"DAEWOO");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (460,"WIERDA VOERTUIG TECHNIEK");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (10,"AUSTIN MORRIS");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (987,"M.O.D. UNIPOWER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (365,"SEDDON");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (161,"ISUZU");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (361,"SAURER");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (25,"BOVA");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (2,"AEC");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (119,"GAZ");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (181,"JCB");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (545,"BREMACH");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (8,"ATKINSON");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (226,"LEYLAND DAF");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (555,"Dulevo");
INSERT INTO `VehMake` (`MakeId`, `Make`) VALUES (459,"MOWAG");
