INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("4P","4 AXLE PSV");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("3D","3 AXLE DRAWBAR TRAILER");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("24","2 AXLE CLASS IV");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("34","3 AXLE CLASS IV");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("2C","2 AXLE CENTRE DRAW-BAR");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("4T","4 AXLE TRACTOR UNIT");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("3S","3 AXLE SEMI-TRAILER");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("3A","3 AXLE ARTICULATED PSV");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("2L","2 AXLE LIGHT MOTOR CAR");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("1C","1 AXLE CENTRE DRAW-BAR");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("SP","SPECIAL PURPOSE VEH/TR");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("3T","3 AXLE TRACTOR UNIT");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("2S","2 AXLE SEMI-TRAILER");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("2R","2 AXLE RIGID HGV");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("1S","1 AXLE SEMI-TRAILER");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("2P","2 AXLE PSV");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("2T","2 AXLE TRACTOR UNIT");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("3L","3 AXLE LIGHT MOTOR CAR");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("1D","1 AXLE DRAWBAR TRAILER");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("4S","4 AXLE SEMI-TRAILER");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("3R","3 AXLE RIGID HGV");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("35","3 AXLE CLASS V");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("25","2 AXLE CLASS V");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("3P","3 AXLE PSV");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("3C","3 AXLE CENTRE DRAW-BAR");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("4R","4 AXLE RIGID HGV");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("37","3 AXLE CLASS VII");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("4A","4 AXLE ARTICULATED PSV");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("4L","4 AXLE LIGHT MOTOR CAR");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("4D","4 AXLE DRAWBAR TRAILER");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("27","2 AXLE CLASS VII");
INSERT INTO `VehType` (`TypeId`, `Type`) VALUES ("2D","2 AXLE DRAWBAR TRAILER");
